# Generated by Django 5.2.7 on 2026-01-19 23:57

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.user_directory_path, verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
