# Generated by Django 5.2.7 on 2025-12-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_picture'),
        ),
    ]
