# Generated by Django 5.2.7 on 2025-12-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_profile_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image3',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_picture'),
        ),
    ]
